name: Deploy Website to AWS

on:
  push:
    branches: [ aws/main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1

      - run: npm ci && npm run build

      - run: |
          aws s3 sync ./.next/static s3://wkw-website-prod --delete \
            --cache-control max-age=31536000

      - run: |
          aws s3 cp ./public/index.html s3://wkw-website-prod/ \
            --cache-control no-cache

      - run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths "/*"
